version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: de_postgres
    environment:
      POSTGRES_USER: dataeng
      POSTGRES_PASSWORD: dataeng123
      POSTGRES_DB: dwh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./platform/storage/warehouse/postgresql:/docker-entrypoint-initdb.d
    networks:
      - data_platform
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataeng"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: de_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - data_platform
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingestion:
    build:
      context: .
      dockerfile: infra/docker/ingestion/Dockerfile
    container_name: de_ingestion
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dataeng
      - POSTGRES_PASSWORD=dataeng123
      - POSTGRES_DB=dwh
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BINANCE_API_BASE=https://api.binance.com
    volumes:
      - ./platform/ingestion:/app/ingestion
      - ./shared:/app/shared
      - ./temp_data_storage:/app/data
      - ./logger_storage:/app/logs
      - ./output:/app/output
    networks:
      - data_platform
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python -m ingestion.crypto.binance.extract.fetch_binance_klines

  dbt:
    build:
      context: .
      dockerfile: infra/docker/processing/Dockerfile
    container_name: de_dbt
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dataeng
      - POSTGRES_PASSWORD=dataeng123
      - POSTGRES_DB=dwh
      - DBT_PROFILES_DIR=/app/processing/dbt
    volumes:
      - ./platform/processing/dbt/binance:/app/dbt_project
      - ./shared:/app/shared
      - ./logger_storage:/app/logs
    networks:
      - data_platform
    depends_on:
      postgres:
        condition: service_healthy
    command: tail -f /dev/null

volumes:
  postgres_data:
  redis_data:

networks:
  data_platform:
    driver: bridge